### ISSUE TITLE
fixing: tke_nrt.cpp:48:18: fatal error: vector: No such file or directory

### ISSUE THREAD

**Issue by juniorprincewang** [SSGAalto/sgx-utils#1]
When compiling the library *lib_tke*, I got error as follows:    
> tke_nrt.cpp:48:18: fatal error: vector: No such file or directory 

According to the SDK reference, vector is supported in SGX SDK.  
I think the library path is just missed from compiling configuration.  
Adding *-I$(SGX_SDK)/include/libcxx* can work.  

>Lib_Include_Paths := -I$(SGX_SDK)/include \
>                        -I$(SGX_SDK)/include/stlport  \
>                         -I$(SGX_SDK)/include/tlibc \
>                         -I$(SGX_SDK)/include/libcxx

**Comment by fritzalder** [comment]
Oops, I did not mean to close it instantly.
I pushed a commit to include your mentioned line and it works for me now. Can you confirm that?

**Comment by juniorprincewang** [comment]
It works.
